enum ISalePhase {
  CLOSED = 'CLOSE',
  GENESIS_PRESALE = 'GENESIS_PRESALE',
  GENESIS_PUBLIC = 'GENESIS_PUBLIC',
  ALPHA_PRESALE = 'ALPHA_PRESALE',
  ALPHA_PUBLIC = 'ALPHA_PUBLIC',
  OPEN_GENESIS_PRESALE = 'OPEN_GENESIS_PRESALE',
  OPEN_GENESIS_SALE = 'OPEN_GENESIS_SALE',
  OPEN_ALPHA_PRESALE = 'OPEN_ALPHA_PRESALE',
  OPEN_ALPHA_SALE = 'OPEN_ALPHA_SALE',
}

export default ISalePhase;
